'use client'

import Link from 'next/link'
import { FormEvent, useEffect, useState } from 'react'
import { Crown, Loader2, Plus, Shield, Trash2 } from 'lucide-react'
import { AuthUser, Course, coursehubApi } from '@/lib/coursehub-api'

export default function AdminPage() {
  const [user, setUser] = useState<AuthUser | null>(null)
  const [courses, setCourses] = useState<Course[]>([])
  const [title, setTitle] = useState('')
  const [description, setDescription] = useState('')
  const [price, setPrice] = useState('')
  const [loading, setLoading] = useState(true)
  const [busy, setBusy] = useState(false)
  const [message, setMessage] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')

  useEffect(() => { coursehubApi.me().then((profile) => { if (profile.role !== 'admin') throw new Error('Admin access required.'); return coursehubApi.adminCourses().then((items) => { setUser(profile); setCourses(items) }) }).catch(() => window.location.assign('/admin/login')).finally(() => setLoading(false)) }, [])
  async function signIn(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); try { const profile = await coursehubApi.login(email, password); if (profile.role !== 'admin') throw new Error('This account does not have admin access.'); setUser(profile); setCourses(await coursehubApi.adminCourses()); setMessage('Welcome to the admin studio.') } catch (reason) { setMessage(reason instanceof Error ? reason.message : 'Admin sign in failed.') } finally { setBusy(false) } }
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); try { const course = await coursehubApi.createCourse({ title, description, price: Number(price), category_id: 1, instructor_id: 1, is_published: true }); setCourses((current) => [course, ...current]); setTitle(''); setDescription(''); setPrice(''); setMessage('Course published successfully.') } catch (reason) { setMessage(reason instanceof Error ? reason.message : 'Unable to publish course.') } finally { setBusy(false) } }
  async function remove(id: number) { setBusy(true); try { await coursehubApi.deleteCourse(id); setCourses((current) => current.filter((course) => course.id !== id)); setMessage('Course removed.') } catch (reason) { setMessage(reason instanceof Error ? reason.message : 'Unable to remove course.') } finally { setBusy(false) } }

  return <main className="min-h-screen bg-background text-foreground"><header className="border-b border-border"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10"><Link href="/" className="flex items-center gap-3"><span className="brand-mark"><Crown size={17} /></span><span className="font-serif text-xl font-semibold text-primary">CourseHub</span></Link><Link href="/" className="text-sm font-semibold text-primary">View collection</Link></div></header><section className="mx-auto max-w-7xl px-6 py-16 lg:px-10"><div className="flex items-center gap-3"><Shield className="text-accent" size={20} /><p className="eyebrow">Admin studio</p></div><h1 className="mt-5 font-serif text-5xl text-primary">Shape the collection.</h1><p className="mt-5 max-w-xl text-lg leading-8 text-muted-foreground">Publish thoughtful courses and keep the CourseHub catalogue worthy of attention.</p>{loading && <div className="mt-12 flex items-center gap-3 text-muted-foreground"><Loader2 className="animate-spin" size={18} /> Loading studio</div>}{message && <p className="mt-6 text-sm font-semibold text-accent" role="status">{message}</p>}{!loading && user?.role === 'admin' && <><form onSubmit={submit} className="mt-12 grid gap-4 border border-border p-6 md:grid-cols-[1fr_1.4fr_160px_auto]"><input required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Course title" className="border border-border bg-background p-3 outline-none focus:border-accent" /><input required value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Description" className="border border-border bg-background p-3 outline-none focus:border-accent" /><input required min="0" type="number" value={price} onChange={(event) => setPrice(event.target.value)} placeholder="Price" className="border border-border bg-background p-3 outline-none focus:border-accent" /><button disabled={busy} className="button-primary inline-flex items-center justify-center gap-2 px-4 py-3">{busy ? <Loader2 className="animate-spin" size={16} /> : <><Plus size={16} /> Publish</>}</button></form><div className="mt-12 divide-y divide-border border-y border-border">{courses.map((course) => <div key={course.id} className="flex items-center justify-between gap-5 py-5"><div><h2 className="font-serif text-2xl text-primary">{course.title}</h2><p className="mt-1 text-sm text-muted-foreground">{course.category?.name ?? 'CourseHub select'} · ${course.price}</p></div><button disabled={busy} onClick={() => remove(course.id)} className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-accent"><Trash2 size={16} /> Remove</button></div>)}</div></>}{!loading && user?.role !== 'admin' && <div className="mt-12 border border-border p-7"><h2 className="font-serif text-3xl text-primary">Admin access required.</h2><p className="mt-3 text-muted-foreground">This studio is reserved for CourseHub administrators.</p></div>}</section></main>
}
