'use client'

import Link from 'next/link'
import { FormEvent, useEffect, useMemo, useState } from 'react'
import { ArrowRight, BookOpen, Check, Crown, Loader2, LogIn, LogOut, MessageCircle, Plus, Search, Shield, Sparkles, Users, X } from 'lucide-react'
import { AuthUser, Course, Enrollment, coursehubApi } from '@/lib/coursehub-api'

const sampleCourses: Course[] = [
  { id: 1, title: 'The Executive Mindset', description: 'A practical masterclass for decisive, thoughtful leadership.', price: '0.00', category: { id: 1, name: 'Leadership' }, instructor: { id: 1, name: 'CourseHub Faculty' } },
  { id: 2, title: 'The Art of Clear Thinking', description: 'Build a sharper mental model for complex decisions.', price: '149.00', category: { id: 2, name: 'Strategy' }, instructor: { id: 1, name: 'CourseHub Faculty' } },
  { id: 3, title: 'Presence & Influence', description: 'Communicate with warmth, clarity, and authority.', price: '189.00', category: { id: 3, name: 'Communication' }, instructor: { id: 1, name: 'CourseHub Faculty' } },
]

export default function Page() {
  const [courses, setCourses] = useState<Course[]>([])
  const [selected, setSelected] = useState<Course | null>(null)
  const [search, setSearch] = useState('')
  const [user, setUser] = useState<AuthUser | null>(null)
  const [learning, setLearning] = useState<Enrollment[]>([])
  const [adminCourses, setAdminCourses] = useState<Course[]>([])
  const [notice, setNotice] = useState('')
  const [busy, setBusy] = useState(false)
  const [authOpen, setAuthOpen] = useState(false)
  const [authMode, setAuthMode] = useState<'signin' | 'register'>('signin')
  const [adminOpen, setAdminOpen] = useState(false)
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [firstName, setFirstName] = useState('')
  const [lastName, setLastName] = useState('')
  const [title, setTitle] = useState('')
  const [description, setDescription] = useState('')
  const [price, setPrice] = useState('')

  useEffect(() => {
    coursehubApi.listCourses().then((data) => setCourses(data.items)).catch((error) => { setCourses(sampleCourses); setNotice(error instanceof Error ? error.message : 'The live catalog is unavailable.') })
    coursehubApi.me().then(loadProfile).catch(() => undefined)
  }, [])

  async function loadProfile(profile: AuthUser) {
    setUser(profile)
    if (profile.role === 'admin') coursehubApi.adminCourses().then(setAdminCourses).catch(() => undefined)
    else coursehubApi.myLearning().then(setLearning).catch(() => undefined)
  }
  async function submitAuth(event: FormEvent) {
    event.preventDefault(); setBusy(true); setNotice('')
    try {
      const profile = authMode === 'signin' ? await coursehubApi.login(email, password) : await coursehubApi.register(email, password, firstName, lastName)
      await loadProfile(profile); setAuthOpen(false); setNotice(authMode === 'signin' ? `Welcome back${profile.first_name ? `, ${profile.first_name}` : ''}.` : 'Your learner account is ready.')
    } catch (error) { setNotice(error instanceof Error ? error.message : 'Authentication failed. Check FastAPI and your credentials.') } finally { setBusy(false) }
  }
  async function enroll(id: number) {
    if (!user) { setAuthMode('signin'); setAuthOpen(true); return }
    setBusy(true)
    try {
      const course = courses.find((item) => item.id === id)
      const result = await coursehubApi.enroll(id)
      setLearning((current) => current.some((item) => item.id === result.enrollment.id) ? current : [result.enrollment, ...current])
      setNotice(result.already_enrolled ? 'You are already enrolled. Your place is saved.' : 'You are enrolled. WhatsApp is ready with your course details.')
      const message = `Hello CourseHub, I ${result.already_enrolled ? 'am following up about' : 'have enrolled in'} "${course?.title ?? result.enrollment.course_title}". My email is ${user.email}.`
      window.open(`https://wa.me/919360226456?text=${encodeURIComponent(message)}`, '_blank', 'noopener,noreferrer')
    } catch (error) { setNotice(error instanceof Error ? error.message : 'Enrollment failed.') } finally { setBusy(false) }
  }
  async function createCourse(event: FormEvent) {
    event.preventDefault(); setBusy(true)
    try { const created = await coursehubApi.createCourse({ title, description, price: Number(price), category_id: 1, instructor_id: 1, is_published: true }); setAdminCourses((current) => [created, ...current]); setCourses((current) => [created, ...current]); setTitle(''); setDescription(''); setPrice(''); setNotice('Course published successfully.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to create course.') } finally { setBusy(false) }
  }
  async function signOut() { await coursehubApi.logout(); setUser(null); setLearning([]); setAdminCourses([]); setAdminOpen(false); setNotice('You have been signed out.') }
  const filtered = useMemo(() => courses.filter((course) => `${course.title} ${course.category?.name ?? ''}`.toLowerCase().includes(search.toLowerCase())), [courses, search])
  const enrolledIds = new Set(learning.map((item) => item.course_id))
  const username = user ? (user.first_name || user.last_name ? `${user.first_name} ${user.last_name}`.trim() : user.email.split('@')[0]) : ''

  return <main className="min-h-screen overflow-hidden bg-background text-foreground">
    <section className="hero-shell"><nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-7 lg:px-10"><a href="#top" className="flex items-center gap-3"><span className="brand-mark"><Crown size={17} /></span><span className="font-serif text-xl font-semibold text-primary">CourseHub</span></a><div className="hidden items-center gap-9 text-sm font-medium text-muted-foreground md:flex"><a href="#courses">Explore courses</a><a href="#learning">My learning</a><a href="#method">Our method</a></div><div className="flex items-center gap-3">{user ? <><span className="hidden max-w-32 truncate text-sm font-semibold text-primary sm:block" title={user.email}>{username}</span><Link href={user.role === 'admin' ? '/admin' : '/learning'} className="hidden items-center gap-2 text-sm font-semibold text-primary sm:flex">{user.role === 'admin' ? <Shield size={15} /> : <BookOpen size={15} />}{user.role === 'admin' ? 'Admin studio' : 'My learning'}</Link><button onClick={signOut} className="hidden items-center gap-2 text-sm text-muted-foreground sm:flex"><LogOut size={15} /> Sign out</button></> : <button onClick={() => { setAuthMode('signin'); setAuthOpen(true) }} className="hidden px-3 py-2 text-sm font-semibold text-primary sm:block">Sign in</button>}<a href="#courses" className="button-primary px-5 py-3 text-sm">Start learning <ArrowRight size={15} /></a></div></nav><div id="top" className="mx-auto grid max-w-7xl items-center gap-14 px-6 pb-20 pt-14 lg:grid-cols-[1.02fr_.98fr] lg:px-10 lg:pb-28 lg:pt-20"><div className="max-w-2xl"><div className="eyebrow"><Sparkles size={14} /> A higher standard of learning</div><h1 className="mt-7 font-serif text-5xl font-medium leading-[1.04] tracking-[-0.04em] text-primary sm:text-6xl lg:text-[5.35rem]">Learn from the <em className="text-accent">remarkable.</em></h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">Premium courses, exceptional instructors, and a learning experience designed to move your ambitions forward.</p><div className="mt-9 flex flex-wrap gap-4"><a href="#courses" className="button-primary px-6 py-4">Explore the collection <ArrowRight size={16} /></a><span className="flex items-center gap-2 px-3 text-sm text-muted-foreground"><Users size={16} /> Curated for curious minds</span></div></div><div className="hero-feature"><div className="feature-label">Featured masterclass</div><div className="feature-art"><Crown size={42} /></div><div className="p-6"><p className="text-xs uppercase tracking-[.2em] text-accent">Leadership / 06 chapters</p><h2 className="mt-3 font-serif text-3xl text-primary">The Executive Mindset</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">A considered approach to making decisions that matter.</p><button onClick={() => setSelected(courses[0] ?? sampleCourses[0])} className="mt-6 flex items-center gap-2 text-sm font-semibold text-primary">View masterclass <ArrowRight size={15} /></button></div></div></div></section>
    <section id="courses" className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="flex flex-col justify-between gap-5 border-b border-border pb-8 sm:flex-row sm:items-end"><div><p className="eyebrow">The collection</p><h2 className="mt-4 font-serif text-4xl tracking-tight text-primary sm:text-5xl">Ideas worth investing in.</h2></div><label className="flex items-center gap-2 border-b border-border pb-2 text-sm text-muted-foreground"><Search size={16} /><span className="sr-only">Search courses</span><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search courses" className="w-40 bg-transparent outline-none placeholder:text-muted-foreground" /></label></div>{notice && <p className="mt-5 text-sm font-medium text-accent" role="status">{notice}</p>}<div className="mt-10 grid gap-6 lg:grid-cols-3">{filtered.map((course, index) => <article key={course.id} className="course-card"><div className={`course-image ${['course-sapphire', 'course-ink', 'course-gold'][index % 3]}`}><span className="course-category">{course.category?.name ?? 'CourseHub select'}</span><BookOpen className="course-watermark" size={64} strokeWidth={0.8} /><span className="course-index">{String(index + 1).padStart(2, '0')}</span></div><div className="p-6"><div className="flex items-center justify-between text-xs text-muted-foreground"><span>{course.duration ?? 'Self-paced'}</span><span>Premium access</span></div><h3 className="mt-3 font-serif text-2xl text-primary">{course.title}</h3><p className="mt-2 text-sm text-muted-foreground">{course.instructor?.name}</p><p className="mt-3 text-sm leading-6 text-muted-foreground">{course.description}</p><div className="mt-6 flex items-center justify-between border-t border-border pt-5"><span className="text-xs text-muted-foreground">{course.price ? `$${course.price}` : 'Included'}</span><div className="flex gap-4"><button onClick={() => window.location.assign(`/courses/${course.id}`)} className="text-sm font-semibold text-primary underline decoration-accent underline-offset-4">Details</button><button onClick={() => enroll(course.id)} disabled={busy} className="text-sm font-semibold text-primary underline decoration-accent underline-offset-4">{enrolledIds.has(course.id) ? 'Enrolled' : busy ? 'Working…' : 'Enroll'}</button></div></div></div></article>)}{!filtered.length && <p className="text-muted-foreground">No courses match your search.</p>}</div></section>
    {user?.role === 'learner' && <section id="learning" className="midnight-section"><div className="mx-auto max-w-7xl px-6 py-20 lg:px-10"><div className="flex items-end justify-between"><div><p className="eyebrow eyebrow-light">Your private library</p><h2 className="mt-4 font-serif text-4xl text-primary-foreground">My learning.</h2></div><BookOpen className="text-accent" /></div><div className="mt-8 grid gap-4 md:grid-cols-3">{learning.length ? learning.map((item) => <div key={item.id} className="border border-primary-foreground/20 p-5"><p className="text-xs text-accent">ENROLLED</p><h3 className="mt-3 font-serif text-2xl text-primary-foreground">{item.course_title}</h3><p className="mt-2 text-sm text-primary-foreground/60">Enrolled {new Date(item.enrolled_at).toLocaleDateString()}</p><button onClick={() => setNotice(`Continue learning: ${item.course_title}`)} className="mt-5 text-sm text-primary-foreground underline decoration-accent underline-offset-4">Continue learning</button></div>) : <p className="text-primary-foreground/65">Your first chapter is waiting in the collection above.</p>}</div></div></section>}
    {adminOpen && user?.role === 'admin' && <section className="mx-auto max-w-7xl px-6 py-20 lg:px-10"><div className="border-b border-border pb-6"><p className="eyebrow">Admin studio</p><h2 className="mt-3 font-serif text-4xl text-primary">Shape the collection.</h2></div><form onSubmit={createCourse} className="mt-8 grid gap-4 border border-border p-6 md:grid-cols-4"><input required value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Course title" className="border border-border bg-background p-3 outline-none" /><input required value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Description" className="border border-border bg-background p-3 outline-none" /><input required type="number" min="0" value={price} onChange={(e) => setPrice(e.target.value)} placeholder="Price" className="border border-border bg-background p-3 outline-none" /><button disabled={busy} className="button-primary px-4 py-3">{busy ? <Loader2 className="animate-spin" size={16} /> : <><Plus size={16} /> Publish course</>}</button></form><div className="mt-8 grid gap-3">{adminCourses.map((course) => <div key={course.id} className="flex items-center justify-between border-b border-border py-4"><span className="font-serif text-xl text-primary">{course.title}</span><button onClick={() => coursehubApi.deleteCourse(course.id).then(() => { setAdminCourses((current) => current.filter((item) => item.id !== course.id)); setNotice('Course removed.') }).catch((error) => setNotice(error.message))} className="text-sm text-muted-foreground underline">Remove</button></div>)}</div></section>}
    <section id="method" className="midnight-section"><div className="mx-auto grid max-w-7xl gap-12 px-6 py-24 lg:grid-cols-[.8fr_1.2fr] lg:px-10"><div><p className="eyebrow eyebrow-light">The CourseHub difference</p><h2 className="mt-5 font-serif text-4xl leading-tight text-primary-foreground sm:text-5xl">A more considered way to grow.</h2><p className="mt-6 max-w-md leading-7 text-primary-foreground/65">Great learning should feel less like a task and more like a privilege.</p></div><div className="grid gap-8 sm:grid-cols-3">{['Learn deeply', 'Practice freely', 'Go further'].map((item, index) => <div key={item} className="method-item"><span>0{index + 1}</span><h3>{item}</h3><p>Thoughtful curriculum, built around lasting understanding.</p></div>)}</div></div></section>
    <footer className="mx-auto flex max-w-7xl flex-col gap-5 px-6 py-10 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between lg:px-10"><span className="font-serif text-lg font-semibold text-primary">CourseHub</span><span>© 2026 CourseHub. Learn remarkably.</span></footer>
    {authOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-primary/35 p-6"><div className="w-full max-w-md bg-card p-8 shadow-2xl"><div className="flex items-center justify-between"><div><p className="eyebrow">Member access</p><h2 className="mt-3 font-serif text-3xl text-primary">{authMode === 'signin' ? 'Return to learning.' : 'Join CourseHub.'}</h2></div><button onClick={() => setAuthOpen(false)} aria-label="Close sign in"><X /></button></div><div className="mt-6 flex gap-5 border-b border-border text-sm"><button onClick={() => setAuthMode('signin')} className={`pb-3 ${authMode === 'signin' ? 'border-b-2 border-accent font-semibold text-primary' : 'text-muted-foreground'}`}>Sign in</button><button onClick={() => setAuthMode('register')} className={`pb-3 ${authMode === 'register' ? 'border-b-2 border-accent font-semibold text-primary' : 'text-muted-foreground'}`}>Create account</button></div><form onSubmit={submitAuth} className="mt-6 grid gap-4">{authMode === 'register' && <div className="grid grid-cols-2 gap-3"><input required value={firstName} onChange={(e) => setFirstName(e.target.value)} placeholder="First name" className="border border-border bg-background p-3 outline-none" /><input required value={lastName} onChange={(e) => setLastName(e.target.value)} placeholder="Last name" className="border border-border bg-background p-3 outline-none" /></div>}<label className="grid gap-2 text-sm font-semibold text-primary">Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="border border-border bg-background p-3 font-normal outline-none focus:border-accent" /></label><label className="grid gap-2 text-sm font-semibold text-primary">Password<input required minLength={authMode === 'register' ? 8 : 1} type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="border border-border bg-background p-3 font-normal outline-none focus:border-accent" />{authMode === 'register' && <span className="text-xs font-normal text-muted-foreground">Use at least 8 characters.</span>}</label><button disabled={busy} className="button-primary mt-3 justify-center py-4">{busy ? <Loader2 className="animate-spin" size={17} /> : authMode === 'signin' ? <><LogIn size={16} /> Sign in</> : <><Check size={16} /> Create learner account</>}</button></form></div></div>}
    {selected && <div className="fixed inset-0 z-40 grid place-items-center bg-primary/35 p-6" onClick={() => setSelected(null)}><article className="w-full max-w-lg bg-card p-8 shadow-2xl" onClick={(e) => e.stopPropagation()}><div className="flex justify-between"><p className="eyebrow">Course detail</p><button onClick={() => setSelected(null)} aria-label="Close course detail"><X /></button></div><h2 className="mt-5 font-serif text-4xl text-primary">{selected.title}</h2><p className="mt-4 leading-7 text-muted-foreground">{selected.description}</p><p className="mt-5 text-sm text-muted-foreground">With {selected.instructor.name} · {selected.category.name}</p><button onClick={() => enroll(selected.id)} className="button-primary mt-8 px-5 py-3">{enrolledIds.has(selected.id) ? 'Already enrolled' : 'Enroll now'} <MessageCircle size={15} /></button></article></div>}
  </main>
}
